server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.225.129

aliyun:
  sms:
    accessKeyId: LTAIoW7kZEyJ9gi6
    accessKeySecret: bJ2AYbBqGijg6WqtNHNFI1J7PbhxV8
    template_code: SMS_169898521
    sign_name: 乐优购

